import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Button, Card, PageHeader, Skeleton, buttonClassName } from '../../components/ui';
import { QuizIcon } from '../../components/icons';
import { useClasses } from '../../features/classes/hooks/useClasses';
import { copyBankQuiz, getQuizTaxonomy, listMyBankQuizzes, listQuizBank, publishQuizToBank, unpublishBankQuiz } from '../../services/quiz-bank.service';
import { importQuiz, quizErrorMessage } from '../../services/quiz.service';

function BankCard({ quiz, classes, onCopy, onRemove, mine, busy }) {
  const [classId, setClassId] = useState(classes[0]?.id || '');
  useEffect(() => { if (!classId && classes[0]?.id) setClassId(classes[0].id); }, [classId, classes]);
  return <Card className="qz-bank-card"><div className="qz-bank-card__head"><span>{quiz.subject?.label || quiz.subjectId}</span><small>{quiz.level}</small></div><QuizIcon size={24} /><h3>{quiz.title}</h3><p>{quiz.description || 'Kuis siap disalin ke kelas Anda.'}</p><div className="qz-quiz-meta"><span>{quiz.questionCount} soal</span><span>{quiz.totalPoints} poin</span>{quiz.tags?.map((tag) => <em key={tag}>#{tag}</em>)}</div><small>Dibuat oleh ID {quiz.authorId}</small>{mine ? <Button variant="ghost" size="sm" disabled={busy} onClick={() => onRemove(quiz)}>Tarik dari Bank Kuis</Button> : <div className="qz-bank-card__copy"><select aria-label="Kelas tujuan" value={classId} onChange={(event) => setClassId(event.target.value)}>{classes.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><Button size="sm" disabled={busy || !classId} onClick={() => onCopy(quiz, classId)}>Gunakan sebagai draf</Button></div>}</Card>;
}

export default function QuizBank() {
  const navigate = useNavigate(); const [search] = useSearchParams(); const { classes, status: classStatus } = useClasses(); const uploadRef = useRef(null); const [importClassId, setImportClassId] = useState(''); const [taxonomy, setTaxonomy] = useState({ levels: [], subjects: [] }); const [quizzes, setQuizzes] = useState([]); const [mine, setMine] = useState([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [filter, setFilter] = useState({ level: 'all', subject: 'all' }); const [publish, setPublish] = useState({ level: 'sd', subjectId: 'matematika', tags: '' });
  const source = useMemo(() => ({ classId: search.get('classId') || '', quizId: search.get('quizId') || '' }), [search]);
  const load = useCallback(async (nextFilter) => { setLoading(true); setError(''); try { const [taxonomyData, bank, personal] = await Promise.all([getQuizTaxonomy(), listQuizBank({ level: nextFilter.level, subject: nextFilter.subject }), listMyBankQuizzes()]); setTaxonomy(taxonomyData); setQuizzes(bank); setMine(personal); setPublish((current) => taxonomyData.levels.some((item) => item.id === current.level) ? current : { ...current, level: taxonomyData.levels[0]?.id || 'sd', subjectId: taxonomyData.subjects[0]?.id || 'matematika' }); } catch (caught) { setError(quizErrorMessage(caught)); } finally { setLoading(false); } }, []);
  useEffect(() => { load(filter); }, [filter, load]);
  useEffect(() => { if (!importClassId && classes[0]?.id) setImportClassId(classes[0].id); }, [classes, importClassId]);
  const updateFilter = (patch) => setFilter((current) => ({ ...current, ...patch }));
  const copy = async (quiz, classId) => { setBusy(true); setError(''); try { const created = await copyBankQuiz(quiz.id, classId); navigate(`/teacher/classes/${classId}/quizzes/${created.id}/edit`); } catch (caught) { setError(quizErrorMessage(caught)); } finally { setBusy(false); } };
  const publishSource = async () => { setBusy(true); setError(''); try { await publishQuizToBank({ ...source, level: publish.level, subjectId: publish.subjectId, tags: publish.tags.split(',').map((tag) => tag.trim()).filter(Boolean) }); await load(filter); navigate('/teacher/quiz-bank', { replace: true }); } catch (caught) { setError(quizErrorMessage(caught)); } finally { setBusy(false); } };
  const remove = async (quiz) => { if (!window.confirm(`Tarik "${quiz.title}" dari Bank Kuis? Salinan guru lain tetap aman.`)) return; setBusy(true); try { await unpublishBankQuiz(quiz.id); await load(filter); } catch (caught) { setError(quizErrorMessage(caught)); } finally { setBusy(false); } };
  const importFile = async (event) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file || !importClassId) return; setBusy(true); setError(''); try { const parsed = JSON.parse(await file.text()); const created = await importQuiz(importClassId, parsed); navigate(`/teacher/classes/${importClassId}/quizzes/${created.id}/edit`); } catch (caught) { setError(caught instanceof SyntaxError ? 'File kuis tidak terbaca. Gunakan berkas JSON hasil unduhan Quizzy.' : quizErrorMessage(caught)); } finally { setBusy(false); } };
  const actions = <><select value={importClassId} onChange={(event) => setImportClassId(event.target.value)} aria-label="Kelas tujuan impor"><option value="">Pilih kelas impor</option>{classes.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><input ref={uploadRef} className="qz-sr-only" type="file" accept="application/json,.json" onChange={importFile} /><Button variant="secondary" disabled={!importClassId || busy} onClick={() => uploadRef.current?.click()}>Impor JSON</Button><Link className={buttonClassName({ variant: 'secondary' })} to="/teacher/quizzes">Kuis kelas saya</Link></>;
  return <div className="qz-dashboard qz-enter"><PageHeader eyebrow="Kolaborasi guru" title="Bank Kuis" description="Temukan kuis terbitan guru, gunakan sebagai draf mandiri, atau bagikan karya Anda." actions={actions} />{error ? <div className="qz-inline-state qz-inline-state--error">{error}</div> : null}{source.classId && source.quizId ? <Card className="qz-bank-publish"><div><span className="qz-eyebrow">PUBLIKASIKAN KUIS</span><h2>Bagikan draf yang sudah diterbitkan</h2><p>Guru lain akan menerima salinan draf. Kuis sumber Anda tidak dapat diedit oleh mereka.</p></div><label>Jenjang<select value={publish.level} onChange={(event) => setPublish({ ...publish, level: event.target.value })}>{taxonomy.levels.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Mata pelajaran<select value={publish.subjectId} onChange={(event) => setPublish({ ...publish, subjectId: event.target.value })}>{taxonomy.subjects.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Tag (pisahkan koma)<input value={publish.tags} maxLength={260} onChange={(event) => setPublish({ ...publish, tags: event.target.value })} placeholder="contoh: pecahan, kelas 5" /></label><Button disabled={busy} onClick={publishSource}>{busy ? 'Menerbitkan...' : 'Terbitkan ke Bank Kuis'}</Button></Card> : null}<Card className="qz-bank-filter"><label>Jenjang<select value={filter.level} onChange={(event) => updateFilter({ level: event.target.value })}><option value="all">Semua jenjang</option>{taxonomy.levels.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Mata pelajaran<select value={filter.subject} onChange={(event) => updateFilter({ subject: event.target.value })}><option value="all">Semua mata pelajaran</option>{taxonomy.subjects.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label></Card>{loading || classStatus === 'loading' ? <div className="qz-quiz-grid"><Skeleton height={230} /><Skeleton height={230} /></div> : <><section className="qz-bank-section"><h2>Jelajahi kuis</h2>{quizzes.length ? <div className="qz-quiz-grid">{quizzes.map((quiz) => <BankCard key={quiz.id} quiz={quiz} classes={classes} busy={busy} onCopy={copy} />)}</div> : <Card>Belum ada kuis pada filter ini.</Card>}</section><section className="qz-bank-section"><h2>Kuis saya yang dipublikasikan</h2>{mine.length ? <div className="qz-quiz-grid">{mine.map((quiz) => <BankCard key={quiz.id} quiz={quiz} classes={classes} busy={busy} mine onRemove={remove} />)}</div> : <Card>Publikasikan kuis kelas untuk membagikannya kepada guru lain.</Card>}</section></>}</div>;
}
