import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Button, Card, PageHeader, Skeleton, buttonClassName } from '../../components/ui';
import { ChevronDownIcon, QuizIcon } from '../../components/icons';
import { useClasses } from '../../features/classes/hooks/useClasses';
import { copyBankQuiz, getQuizTaxonomy, listMyBankQuizzes, listQuizBank, publishQuizToBank, unpublishBankQuiz } from '../../services/quiz-bank.service';
import { quizErrorMessage } from '../../services/quiz.service';

function ChoicePicker({ label, value, items, allLabel, onChange }) {
  const selected = items.find((item) => item.id === value);
  const choose = (next, event) => { onChange(next); event.currentTarget.closest('details')?.removeAttribute('open'); };
  return <details className="qz-bank-picker"><summary><span><small>{label}</small><b>{selected?.label || allLabel}</b></span><ChevronDownIcon size={17} /></summary><div className="qz-bank-picker__options" role="listbox" aria-label={label}>{allLabel ? <button type="button" className={value === 'all' ? 'selected' : ''} aria-pressed={value === 'all'} onClick={(event) => choose('all', event)}>{allLabel}</button> : null}{items.map((item) => <button type="button" key={item.id} className={value === item.id ? 'selected' : ''} aria-pressed={value === item.id} onClick={(event) => choose(item.id, event)}>{item.label}</button>)}</div></details>;
}

function BankCard({ quiz, classes, onCopy, onRemove, mine, busy }) {
  const [classId, setClassId] = useState(classes[0]?.id || '');
  useEffect(() => { if (!classId && classes[0]?.id) setClassId(classes[0].id); }, [classId, classes]);
  const selectedClass = classes.find((item) => item.id === classId);
  return <Card className="qz-bank-card"><div className="qz-bank-card__head"><span>{quiz.subject?.label || quiz.subjectId}</span><small>{quiz.level}</small></div><QuizIcon size={24} /><h3>{quiz.title}</h3><p>{quiz.description || 'Kuis siap disalin ke kelas Anda.'}</p><div className="qz-quiz-meta"><span>{quiz.questionCount} soal</span><span>{quiz.totalPoints} poin</span>{quiz.tags?.map((tag) => <em key={tag}>#{tag}</em>)}</div><small>Dibuat oleh ID {quiz.authorId}</small>{mine ? <Button variant="ghost" size="sm" disabled={busy} onClick={() => onRemove(quiz)}>Tarik dari Bank Kuis</Button> : <div className="qz-bank-card__copy"><details className="qz-bank-picker"><summary><span><small>Simpan ke kelas</small><b>{selectedClass?.name || 'Pilih kelas'}</b></span><ChevronDownIcon size={17} /></summary><div className="qz-bank-picker__options" role="listbox" aria-label="Kelas tujuan">{classes.map((item) => <button type="button" key={item.id} className={item.id === classId ? 'selected' : ''} aria-pressed={item.id === classId} onClick={(event) => { setClassId(item.id); event.currentTarget.closest('details')?.removeAttribute('open'); }}>{item.name}</button>)}</div></details><Button size="sm" disabled={busy || !classId} onClick={() => onCopy(quiz, classId)}>Gunakan sebagai draf</Button></div>}</Card>;
}

export default function QuizBank() {
  const navigate = useNavigate(); const [search] = useSearchParams(); const { classes, status: classStatus } = useClasses();
  const [taxonomy, setTaxonomy] = useState({ levels: [], subjects: [] }); const [quizzes, setQuizzes] = useState([]); const [mine, setMine] = useState([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [filter, setFilter] = useState({ level: 'all', subject: 'all' }); const [publish, setPublish] = useState({ level: 'sd', subjectId: 'matematika', tags: '' });
  const source = useMemo(() => ({ sourceType: search.get('source') === 'general' ? 'general' : 'class', classId: search.get('classId') || '', quizId: search.get('quizId') || '' }), [search]);
  const load = useCallback(async (nextFilter) => { setLoading(true); setError(''); try { const [taxonomyData, bank, personal] = await Promise.all([getQuizTaxonomy(), listQuizBank({ level: nextFilter.level, subject: nextFilter.subject }), listMyBankQuizzes()]); setTaxonomy(taxonomyData); setQuizzes(bank); setMine(personal); setPublish((current) => taxonomyData.levels.some((item) => item.id === current.level) ? current : { ...current, level: taxonomyData.levels[0]?.id || 'sd', subjectId: taxonomyData.subjects[0]?.id || 'matematika' }); } catch (caught) { setError(quizErrorMessage(caught)); } finally { setLoading(false); } }, []);
  useEffect(() => { load(filter); }, [filter, load]);
  const copy = async (quiz, classId) => { setBusy(true); setError(''); try { const created = await copyBankQuiz(quiz.id, classId); navigate(`/teacher/classes/${classId}/quizzes/${created.id}/edit`); } catch (caught) { setError(quizErrorMessage(caught)); } finally { setBusy(false); } };
  const publishSource = async () => { setBusy(true); setError(''); try { await publishQuizToBank({ ...source, level: publish.level, subjectId: publish.subjectId, tags: publish.tags.split(',').map((tag) => tag.trim()).filter(Boolean) }); await load(filter); navigate('/teacher/quiz-bank', { replace: true }); } catch (caught) { setError(quizErrorMessage(caught)); } finally { setBusy(false); } };
  const remove = async (quiz) => { if (!window.confirm(`Tarik "${quiz.title}" dari Bank Kuis? Salinan guru lain tetap aman.`)) return; setBusy(true); try { await unpublishBankQuiz(quiz.id); await load(filter); } catch (caught) { setError(quizErrorMessage(caught)); } finally { setBusy(false); } };
  const sourceReady = source.quizId && (source.sourceType === 'general' || source.classId);
  return <div className="qz-dashboard qz-enter"><PageHeader eyebrow="Kolaborasi guru" title="Bank Kuis" description="Temukan kuis terbitan guru, gunakan sebagai draf mandiri, atau bagikan karya Anda." actions={<Link className={buttonClassName({ variant: 'secondary' })} to="/teacher/quizzes">Kembali ke Kuis</Link>} />
    {error ? <div className="qz-inline-state qz-inline-state--error">{error}</div> : null}
    {sourceReady ? <Card className="qz-bank-publish"><div><span className="qz-eyebrow">PUBLIKASIKAN KUIS</span><h2>Bagikan kuis ke komunitas</h2><p>Guru lain menerima salinan draf, sementara kuis sumber Anda tetap aman.</p></div><ChoicePicker label="Jenjang" value={publish.level} items={taxonomy.levels} onChange={(level) => setPublish((current) => ({ ...current, level }))} /><ChoicePicker label="Mata pelajaran" value={publish.subjectId} items={taxonomy.subjects} onChange={(subjectId) => setPublish((current) => ({ ...current, subjectId }))} /><label>Tag (pisahkan koma)<input value={publish.tags} maxLength={260} onChange={(event) => setPublish({ ...publish, tags: event.target.value })} placeholder="contoh: pecahan, kelas 5" /></label><Button disabled={busy} onClick={publishSource}>{busy ? 'Menerbitkan...' : 'Terbitkan ke Bank Kuis'}</Button></Card> : null}
    <Card className="qz-bank-filter"><ChoicePicker label="Jenjang" value={filter.level} items={taxonomy.levels} allLabel="Semua jenjang" onChange={(level) => setFilter((current) => ({ ...current, level }))} /><ChoicePicker label="Mata pelajaran" value={filter.subject} items={taxonomy.subjects} allLabel="Semua mata pelajaran" onChange={(subject) => setFilter((current) => ({ ...current, subject }))} /></Card>
    {loading || classStatus === 'loading' ? <div className="qz-quiz-grid"><Skeleton height={230} /><Skeleton height={230} /></div> : <><section className="qz-bank-section"><h2>Jelajahi kuis</h2>{quizzes.length ? <div className="qz-quiz-grid">{quizzes.map((quiz) => <BankCard key={quiz.id} quiz={quiz} classes={classes} busy={busy} onCopy={copy} />)}</div> : <Card>Belum ada kuis pada filter ini.</Card>}</section><section className="qz-bank-section"><h2>Kuis saya yang dipublikasikan</h2>{mine.length ? <div className="qz-quiz-grid">{mine.map((quiz) => <BankCard key={quiz.id} quiz={quiz} classes={classes} busy={busy} mine onRemove={remove} />)}</div> : <Card>Publikasikan kuis kelas atau kuis umum untuk membagikannya kepada guru lain.</Card>}</section></>}
  </div>;
}
