import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import ClassWorkspaceNav from '../../components/classroom/ClassWorkspaceNav';
import { Button, Card, Input, PageHeader, Textarea, buttonClassName } from '../../components/ui';
import { createTask, getTask, taskErrorMessage, updateTask } from '../../services/task.service';

function localDateTime(hours = 168) { const date = new Date(Date.now() + hours * 60 * 60 * 1000); date.setMinutes(0, 0, 0); return date.toISOString().slice(0, 16); }

export default function TaskEditor() {
  const { classId, taskId } = useParams(); const navigate = useNavigate();
  const [form, setForm] = useState({ title: '', instructions: '', dueAt: localDateTime(), responseMode: 'both', status: 'published' }); const [busy, setBusy] = useState(Boolean(taskId)); const [error, setError] = useState('');
  useEffect(() => { if (!taskId) return undefined; let active = true; getTask(classId, taskId).then((task) => { if (active) { setForm({ title: task.title, instructions: task.instructions, dueAt: task.dueAt.slice(0, 16), responseMode: task.responseMode, status: task.status }); setBusy(false); } }).catch((caught) => { if (active) { setError(taskErrorMessage(caught)); setBusy(false); } }); return () => { active = false; }; }, [classId, taskId]);
  const set = (name) => (event) => setForm((current) => ({ ...current, [name]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const input = { ...form, dueAt: new Date(form.dueAt).toISOString() }; const task = taskId ? await updateTask(classId, taskId, input) : await createTask(classId, input); navigate(`/teacher/classes/${classId}/tasks/${task.id}`, { replace: true }); } catch (caught) { setError(taskErrorMessage(caught)); } finally { setBusy(false); } };
  return <div className="qz-dashboard qz-enter"><PageHeader eyebrow="Ruang guru" title={taskId ? 'Edit tugas' : 'Buat tugas'} description="Tugas terlambat tetap dapat dikirim dan akan ditandai merah untuk guru." actions={<Link to={`/teacher/classes/${classId}/tasks`} className={buttonClassName({ variant: 'secondary' })}>Kembali</Link>} /><ClassWorkspaceNav role="teacher" classId={classId} />
    <form className="qz-task-editor" onSubmit={submit}><Card><div className="qz-task-editor__body"><Input label="Judul tugas" value={form.title} onChange={set('title')} required minLength="3" maxLength="160" placeholder="Contoh: Refleksi Bab 1" /><Textarea label="Petunjuk" value={form.instructions} onChange={set('instructions')} maxLength="5000" rows="7" placeholder="Jelaskan apa yang perlu dikumpulkan siswa." /><Input label="Tenggat" type="datetime-local" value={form.dueAt} onChange={set('dueAt')} required /><label className="qz-field"><span className="qz-field__label">Bentuk jawaban</span><select className="qz-input" value={form.responseMode} onChange={set('responseMode')}><option value="text">Teks</option><option value="attachment">Lampiran</option><option value="both">Teks dan lampiran</option></select></label><label className="qz-field"><span className="qz-field__label">Status</span><select className="qz-input" value={form.status} onChange={set('status')}><option value="published">Terbitkan sekarang</option><option value="draft">Simpan draf</option><option value="archived">Arsipkan</option></select></label>{error ? <div className="qz-inline-state qz-inline-state--error" role="alert">{error}</div> : null}<div className="qz-task-editor__actions"><Button type="button" variant="secondary" disabled={busy} onClick={() => navigate(-1)}>Batal</Button><Button type="submit" disabled={busy}>{busy ? 'Menyimpan...' : taskId ? 'Simpan perubahan' : form.status === 'published' ? 'Terbitkan tugas' : 'Simpan draf'}</Button></div></div></Card></form>
  </div>;
}
