import { useEffect, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { Link, useParams } from 'react-router-dom';
import { Button, Card, Input, PageHeader, buttonClassName } from '../components/ui';
import { advanceLiveSession, createLiveSession, getLiveHostSession, liveQuizErrorMessage } from '../services/live-quiz.service';

export default function LiveQuizHost() {
  const { classId, quizId } = useParams(); const [duration, setDuration] = useState(30); const [session, setSession] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!session?.id || session.phase === 'finished') return undefined; const refresh = () => getLiveHostSession(classId, session.id).then(setSession).catch((caught) => setError(liveQuizErrorMessage(caught))); const timer = window.setInterval(refresh, 2000); return () => window.clearInterval(timer); }, [classId, session?.id, session?.phase]);
  const create = async () => { setBusy(true); setError(''); try { setSession(await createLiveSession(classId, quizId, { questionDurationSeconds: Number(duration) })); } catch (caught) { setError(liveQuizErrorMessage(caught)); } finally { setBusy(false); } };
  const action = async (name) => { setBusy(true); setError(''); try { setSession(await advanceLiveSession(classId, session.id, name)); } catch (caught) { setError(liveQuizErrorMessage(caught)); } finally { setBusy(false); } };
  const joinUrl = `${window.location.origin}/quiz/join/${session?.code || ''}`;
  const buttonLabel = session?.phase === 'lobby' ? 'Mulai soal pertama' : session?.phase === 'question' ? 'Kunci & tampilkan jawaban' : session?.phase === 'reveal' ? 'Soal berikutnya' : 'Sesi selesai';
  return <div className="qz-dashboard qz-enter"><PageHeader eyebrow="Host live" title={session?.title || 'Mulai kuis live'} description="Bagikan QR atau kode sesi. Peserta dapat langsung masuk tanpa akun dan tanpa bergabung ke kelas." actions={<Link className={buttonClassName({ variant: 'secondary' })} to={`/teacher/classes/${classId}/quizzes`}>Kembali</Link>} />
    {error ? <div className="qz-inline-state qz-inline-state--error" role="alert">{error}</div> : null}
    {!session ? <Card className="qz-live-create"><h2>Siapkan arena</h2><p>Timer dihitung di perangkat setiap peserta dari waktu server, bukan dari hitungan mundur yang terus dikirimkan.</p><Input label="Durasi per soal (detik)" type="number" min="5" max="300" value={duration} onChange={(event) => setDuration(event.target.value)} /><Button disabled={busy} onClick={create}>{busy ? 'Membuat sesi...' : 'Buat sesi live'}</Button></Card> : <div className="qz-live-host">
      <Card className="qz-live-code"><div><span className="qz-eyebrow">KODE KUIS</span><strong>{session.code}</strong><p>{session.participantCount} peserta di lobi</p><button type="button" className="qz-live-link" onClick={() => navigator.clipboard?.writeText(joinUrl)}>Salin tautan gabung</button></div><QRCodeSVG value={joinUrl} size={164} level="M" includeMargin /></Card>
      <Card className="qz-live-stage"><div className="qz-live-stage__meta"><span className={`qz-live-phase qz-live-phase--${session.phase}`}>{session.phase === 'lobby' ? 'Lobi terbuka' : session.phase === 'question' ? `Soal ${session.questionIndex + 1}` : session.phase === 'reveal' ? 'Pembahasan' : 'Selesai'}</span><span>{session.questionCount} soal</span>{session.phase === 'question' ? <span>{session.answeredCount}/{session.participantCount} menjawab</span> : null}</div><h2>{session.question?.prompt || 'Tunggu peserta bergabung, lalu mulai saat siap.'}</h2>{session.question?.choices ? <div className="qz-live-choice-preview">{session.question.choices.map((choice, index) => <span key={choice}><i>{String.fromCharCode(65 + index)}</i>{choice}</span>)}</div> : null}{['question', 'reveal'].includes(session.phase) && Object.keys(session.optionCounts || {}).length ? <div className="qz-live-distribution">{Object.entries(session.optionCounts).map(([choice, count]) => <div key={choice}><span>{choice}</span><b style={{ width: `${Math.round((count / Math.max(session.answeredCount, 1)) * 100)}%` }} /><strong>{count}</strong></div>)}</div> : null}{session.phase === 'reveal' && session.question ? <div className="qz-live-reveal"><strong>Jawaban benar: {String(session.question.correctAnswer)}</strong>{session.question.explanation ? <p>{session.question.explanation}</p> : null}</div> : null}<div className="qz-live-host__actions">{session.phase !== 'finished' ? <Button disabled={busy} onClick={() => action('advance')}>{busy ? 'Memperbarui...' : buttonLabel}</Button> : null}{session.phase !== 'finished' ? <Button variant="secondary" disabled={busy} onClick={() => action('finish')}>Akhiri sesi</Button> : null}</div></Card>
      <Card className="qz-live-participants"><h2>Peserta ({session.participants?.length || 0})</h2><div>{session.participants?.length ? session.participants.map((participant) => <span key={participant.id}>{participant.name}{session.phase === 'finished' ? ` · ${participant.score} poin` : ''}</span>) : <p>Belum ada peserta. Tampilkan QR atau kode di layar host.</p>}</div></Card>{session.phase === 'finished' ? <Card className="qz-live-results"><span className="qz-eyebrow">PAPAN SKOR AKHIR</span><h2>Selamat untuk para pemain!</h2>{session.leaderboard?.length ? <ol>{session.leaderboard.slice(0, 10).map((participant) => <li key={participant.id}><b>#{participant.rank}</b><span>{participant.name}</span><strong>{participant.score} poin</strong></li>)}</ol> : <p>Belum ada jawaban yang selesai diproses.</p>}</Card> : null}
    </div>}</div>;
}
