import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Card, PageHeader, buttonClassName } from '../components/ui';
import { answerLiveQuestion, getLiveParticipantResult, getLiveSession, liveQuizErrorMessage } from '../services/live-quiz.service';

const storageKey = (code) => `quizzy.live.${code.toUpperCase()}`;
function LiveInteractiveAnswer({ question, value, onChange }) {
  const [dragging, setDragging] = useState(null);
  if (question.type === 'arrange') { const order = Array.isArray(value) && value.length ? value : (question.items || []).map((item) => item.id); const map = new Map((question.items || []).map((item) => [item.id, item])); const move = (from, to) => { const next = [...order]; const [item] = next.splice(from, 1); next.splice(to, 0, item); onChange(next); }; return <ol className="qz-arrange-answer">{order.map((id, index) => <li draggable key={id} onDragStart={() => setDragging(index)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); if (dragging !== null) move(dragging, index); }}><span>⠿</span>{map.get(id)?.text}<button type="button" disabled={index === 0} onClick={() => move(index, index - 1)}>↑</button><button type="button" disabled={index === order.length - 1} onClick={() => move(index, index + 1)}>↓</button></li>)}</ol>; }
  if (question.type === 'image_hotspot') return <div className="qz-hotspot-answer" onClick={(event) => { const box = event.currentTarget.getBoundingClientRect(); onChange({ x: Math.max(0, Math.min(100, ((event.clientX - box.left) / box.width) * 100)), y: Math.max(0, Math.min(100, ((event.clientY - box.top) / box.height) * 100)) }); }}><img src={question.imageUrl} alt="Gambar untuk dijawab" /><span className="qz-hotspot-answer__hint">Klik bagian yang benar</span>{value && typeof value === 'object' ? <i style={{ left: `${value.x}%`, top: `${value.y}%` }} /> : null}</div>;
  if (question.type === 'short_answer') return <input className="qz-answer-input" value={value || ''} onChange={(event) => onChange(event.target.value)} placeholder="Tulis jawabanmu" />;
  const choices = question.type === 'true_false' ? [{ label: 'Benar', value: true }, { label: 'Salah', value: false }] : question.choices.map((label) => ({ label, value: label })); return <div className="qz-live-answer-grid">{choices.map((choice, index) => <button type="button" key={choice.label} className={String(value) === String(choice.value) ? 'selected' : ''} onClick={() => onChange(choice.value)}><i>{String.fromCharCode(65 + index)}</i>{choice.label}</button>)}</div>;
}
export default function LiveQuizPlayer() {
  const { code } = useParams(); const [state, setState] = useState(null); const [answer, setAnswer] = useState(''); const [receipt, setReceipt] = useState(null); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [now, setNow] = useState(Date.now()); const participant = useMemo(() => { try { return JSON.parse(sessionStorage.getItem(storageKey(code)) || 'null'); } catch { return null; } }, [code]);
  useEffect(() => { const load = () => getLiveSession(code).then(setState).catch((caught) => setError(liveQuizErrorMessage(caught))); load(); const poll = window.setInterval(load, 2000); const clock = window.setInterval(() => setNow(Date.now()), 250); return () => { window.clearInterval(poll); window.clearInterval(clock); }; }, [code]);
  useEffect(() => { setAnswer(''); setReceipt(null); }, [state?.question?.id]); const seconds = state?.endsAt ? Math.max(0, Math.ceil((new Date(state.endsAt).getTime() - now) / 1000)) : 0; const hasAnswer = Array.isArray(answer) ? answer.length > 0 : answer && typeof answer === 'object' ? true : answer !== '';
  useEffect(() => { if (state?.phase !== 'finished' || !participant) return undefined; let cancelled = false; const loadResult = () => getLiveParticipantResult(code, participant).then((next) => { if (!cancelled) setResult(next); }).catch((caught) => { if (!cancelled && caught?.code !== 'LIVE_RESULT_NOT_READY') setError(liveQuizErrorMessage(caught)); }); loadResult(); const timer = window.setInterval(loadResult, 2000); return () => { cancelled = true; window.clearInterval(timer); }; }, [code, participant, state?.phase]);
  const submit = async () => { if (!participant || !state?.question || receipt) return; try { setReceipt(await answerLiveQuestion(code, { ...participant, questionId: state.question.id, answer })); } catch (caught) { setError(liveQuizErrorMessage(caught)); } };
  if (!participant) return <div className="qz-live-public"><PageHeader title="Sesi peserta tidak ditemukan" description="Masuk kembali menggunakan kode kuis dan nama yang sama." /><Link to={`/quiz/join/${code || ''}`} className={buttonClassName()}>Kembali ke gabung kuis</Link></div>;
  return <div className="qz-live-public qz-enter"><PageHeader eyebrow={`Halo, ${participant.name}`} title={state?.title || 'Menyiapkan kuis'} description={state?.phase === 'lobby' ? 'Kamu sudah masuk. Tunggu host memulai kuis.' : 'Jawab dari perangkatmu. Layar akan mengikuti host secara otomatis.'} />{error ? <div className="qz-inline-state qz-inline-state--error">{error}</div> : null}{state?.phase === 'question' && state.question ? <Card className="qz-live-player-card"><div className="qz-live-timer"><span>{seconds}</span> detik</div><span className="qz-eyebrow">SOAL {state.questionIndex + 1} DARI {state.questionCount}</span><h1>{state.question.prompt}</h1><LiveInteractiveAnswer question={state.question} value={answer} onChange={setAnswer} /><Button block disabled={!hasAnswer || Boolean(receipt) || seconds === 0} onClick={submit}>{receipt ? 'Jawaban diterima!' : 'Kunci jawaban'}</Button></Card> : state?.phase === 'reveal' && state.question ? <Card className="qz-live-reveal qz-live-reveal--player"><span className="qz-live-wait__spark">✦</span><span className="qz-eyebrow">PEMBAHASAN</span><h2>{state.question.prompt}</h2><strong>Jawaban benar: {Array.isArray(state.question.correctAnswer) ? 'Susunan yang ditetapkan guru' : String(state.question.correctAnswer)}</strong>{state.question.explanation ? <p>{state.question.explanation}</p> : null}</Card> : state?.phase === 'finished' && result ? <Card className="qz-live-result"><span className="qz-live-wait__spark">✦</span><span className="qz-eyebrow">HASIL AKHIR</span><h2>Keren, {result.participant.name}!</h2><strong>{result.participant.score} poin</strong><p>{result.participant.correctCount} jawaban benar dari {result.questionCount} soal · Peringkat #{result.participant.rank}</p></Card> : <Card className="qz-live-wait"><span className="qz-live-wait__spark">✦</span><h2>{state?.phase === 'finished' ? 'Menghitung hasilmu...' : 'Kamu sudah di lobi!'}</h2><p>{state?.phase === 'finished' ? 'Jawaban terakhir sedang diamankan.' : 'Tetap di halaman ini. Soal berikutnya akan muncul otomatis.'}</p></Card>}</div>;
}
