import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Save, UserRound } from 'lucide-react';
import { Button, Card, Input, PageHeader } from '../components/ui';
import { homeForRole } from '../app/navigation';
import { useAuth } from '../context/useAuth';

const genderOptions = [{ value: '', label: 'Pilih jenis kelamin' }, { value: 'female', label: 'Perempuan' }, { value: 'male', label: 'Laki-laki' }, { value: 'prefer_not_to_say', label: 'Memilih untuk tidak menyebutkan' }];

export default function Profile({ onboarding = false, onComplete }) {
  const { user, userProfile, saveUserProfile } = useAuth(); const navigate = useNavigate();
  const initial = useMemo(() => ({ name: userProfile?.name || user?.displayName || '', nickname: userProfile?.nickname || '', subject: userProfile?.subject || (userProfile?.role === 'student' ? '' : 'Umum'), institution: userProfile?.institution || '', gender: userProfile?.gender || '' }), [user, userProfile]);
  const [form, setForm] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); setError(''); if (!form.name.trim() || !form.nickname.trim() || !form.subject.trim() || !form.institution.trim() || !form.gender) return setError('Lengkapi seluruh profil wajib sebelum melanjutkan.'); setBusy(true); try { const now = new Date().toISOString(); const next = { uid: user.uid, name: form.name.trim(), nickname: form.nickname.trim(), email: user?.email || userProfile?.email || '', role: userProfile?.role || 'student', subject: form.subject.trim(), institution: form.institution.trim(), gender: form.gender, avatar: userProfile?.avatar || user?.photoURL || null, isAnonymous: Boolean(userProfile?.isAnonymous), profileCompleted: true, createdAt: userProfile?.createdAt || now, updatedAt: now }; await saveUserProfile(user.uid, next); if (onComplete) onComplete(next.role); else navigate(homeForRole(next.role)); } catch (caught) { setError(caught?.code === 'permission-denied' ? 'Profil ditolak oleh aturan penyimpanan. Perbarui Firestore Rules lalu coba lagi.' : 'Profil belum dapat disimpan. Coba lagi.'); } finally { setBusy(false); } };
  const roleLabel = userProfile?.role === 'student' ? 'Siswa' : 'Guru';
  const learningLabel = roleLabel === 'Siswa' ? 'Kelas / semester' : 'Bidang mata pelajaran / bidang belajar';
  const learningPlaceholder = roleLabel === 'Siswa' ? 'Contoh: Kelas XI / Semester 1' : 'Contoh: Matematika, Umum, Teknik Jaringan';
  return <div className={onboarding ? 'qz-profile-onboarding' : 'qz-dashboard qz-enter'}>{onboarding ? <div className="qz-profile-onboarding__intro"><span><UserRound size={21} /></span><div><b>Selangkah lagi</b><p>Lengkapi profil agar ruang belajar Anda terasa lebih personal.</p></div></div> : <PageHeader eyebrow="Akun saya" title="Profil" description="Perbarui informasi yang tampil di ruang belajar." />}<Card className="qz-profile-card"><form className="qz-profile-form" onSubmit={submit}><div className="qz-profile-form__role"><span>Status akun</span><b>{roleLabel}</b><small>Peran dibuat saat pendaftaran dan tidak dapat diubah dari profil.</small></div><Input label="Nama lengkap" required value={form.name} maxLength={100} onChange={(event) => update('name', event.target.value)} /><Input label="Nama panggilan" required value={form.nickname} maxLength={40} onChange={(event) => update('nickname', event.target.value)} /><Input label="Email" value={user?.email || userProfile?.email || 'Akun tamu'} disabled /><Input label="Asal sekolah / institusi" required value={form.institution} maxLength={160} placeholder="Contoh: SMA Negeri 1 Tegal" onChange={(event) => update('institution', event.target.value)} /><Input label={learningLabel} required value={form.subject} maxLength={100} placeholder={learningPlaceholder} onChange={(event) => update('subject', event.target.value)} /><label className="qz-field"><span>Jenis kelamin</span><select required value={form.gender} onChange={(event) => update('gender', event.target.value)}>{genderOptions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>{error ? <p className="qz-field-error" role="alert">{error}</p> : null}<Button type="submit" disabled={busy}>{busy ? 'Menyimpan...' : <><Save size={17} /> {onboarding ? 'Simpan dan masuk' : 'Simpan perubahan'}</>}</Button></form></Card></div>;
}
