import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Card, PageHeader, buttonClassName } from '../components/ui';
import { getQuiz, quizErrorMessage, submitQuiz } from '../services/quiz.service';

function ArrangeAnswer({ question, value, onChange }) {
  const [dragging, setDragging] = useState(null); const order = Array.isArray(value) && value.length ? value : (question.items || []).map((item) => item.id).sort(() => Math.random() - .5); const items = new Map((question.items || []).map((item) => [item.id, item]));
  const move = (from, to) => { const next = [...order]; const [item] = next.splice(from, 1); next.splice(to, 0, item); onChange(next); };
  return <ol className="qz-arrange-answer">{order.map((id, index) => <li key={id} draggable onDragStart={() => setDragging(index)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); if (dragging !== null) move(dragging, index); setDragging(null); }}><span>⠿</span>{items.get(id)?.text}<button type="button" aria-label="Naik" disabled={index === 0} onClick={() => move(index, index - 1)}>↑</button><button type="button" aria-label="Turun" disabled={index === order.length - 1} onClick={() => move(index, index + 1)}>↓</button></li>)}</ol>;
}
function HotspotAnswer({ question, value, onChange }) {
  const choose = (event) => { const box = event.currentTarget.getBoundingClientRect(); onChange({ x: Math.max(0, Math.min(100, ((event.clientX - box.left) / box.width) * 100)), y: Math.max(0, Math.min(100, ((event.clientY - box.top) / box.height) * 100)) }); };
  return <div className="qz-hotspot-answer" onClick={choose}><img src={question.imageUrl} alt="Gambar untuk dijawab" /><span className="qz-hotspot-answer__hint">Klik bagian yang menurutmu benar</span>{value && typeof value === 'object' ? <i style={{ left: `${value.x}%`, top: `${value.y}%` }} /> : null}</div>;
}
function AnswerInput({ question, value, onChange }) {
  if (question.type === 'multiple_choice') return <div className="qz-choice-list">{question.choices.map((choice) => <label key={choice}><input type="radio" name={question.id} checked={value === choice} onChange={() => onChange(choice)} /> {choice}</label>)}</div>;
  if (question.type === 'true_false') return <div className="qz-choice-list">{['true', 'false'].map((item) => <label key={item}><input type="radio" name={question.id} checked={String(value) === item} onChange={() => onChange(item === 'true')} /> {item === 'true' ? 'Benar' : 'Salah'}</label>)}</div>;
  if (question.type === 'arrange') return <ArrangeAnswer question={question} value={value} onChange={onChange} />;
  if (question.type === 'image_hotspot') return <HotspotAnswer question={question} value={value} onChange={onChange} />;
  return <input className="qz-answer-input" value={value || ''} onChange={(event) => onChange(event.target.value)} placeholder="Tulis jawabanmu" />;
}

export default function QuizAttempt() {
  const { classId, quizId } = useParams(); const [quiz, setQuiz] = useState(null); const [answers, setAnswers] = useState({}); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(true);
  useEffect(() => { const controller = new AbortController(); getQuiz(classId, quizId, { signal: controller.signal }).then(setQuiz).catch((caught) => { if (caught.name !== 'AbortError') setError(quizErrorMessage(caught)); }).finally(() => setBusy(false)); return () => controller.abort(); }, [classId, quizId]);
  const questions = useMemo(() => { if (!quiz) return []; const items = [...quiz.questions]; if (!quiz.settings?.shuffleQuestions) return items; for (let index = items.length - 1; index > 0; index -= 1) { const random = new Uint32Array(1); crypto.getRandomValues(random); const target = random[0] % (index + 1); [items[index], items[target]] = [items[target], items[index]]; } return items; }, [quiz]);
  const submit = async () => { setBusy(true); setError(''); try { setResult(await submitQuiz(classId, quizId, questions.map((question) => ({ questionId: question.id, answer: answers[question.id] ?? '' })))); } catch (caught) { setError(quizErrorMessage(caught)); } finally { setBusy(false); } };
  if (result) return <div className="qz-dashboard qz-enter"><PageHeader eyebrow="Hasil kuis" title={quiz.title} description="Jawabanmu sudah dinilai oleh Quizzy." /><Card className="qz-quiz-score"><span>Nilai akhir</span><strong>{result.score}</strong><p>{result.passed ? 'Kamu mencapai nilai kelulusan.' : 'Nilaimu belum mencapai batas kelulusan.'}</p><small>{result.earnedPoints} dari {result.totalPoints} poin</small></Card>{result.review?.map((item, index) => <Card className="qz-review" key={item.questionId}><strong>{index + 1}. {item.prompt}</strong><p>Jawabanmu: {Array.isArray(item.answer) ? item.answer.join(' → ') : typeof item.answer === 'object' ? 'Titik pada gambar' : String(item.answer) || 'Tidak dijawab'}</p><p>Jawaban benar: {Array.isArray(item.correctAnswer) ? item.correctAnswer.join(' → ') : String(item.correctAnswer)}</p>{item.explanation ? <small>{item.explanation}</small> : null}</Card>)}<Link className={buttonClassName({ variant: 'secondary' })} to={`/student/classes/${classId}/quizzes`}>Kembali ke daftar kuis</Link></div>;
  return <div className="qz-dashboard qz-enter"><PageHeader eyebrow="Kuis mandiri" title={quiz?.title || 'Memuat kuis...'} description={quiz?.description} actions={<Link className={buttonClassName({ variant: 'secondary' })} to={`/student/classes/${classId}/quizzes`}>Keluar</Link>} />{error ? <div className="qz-inline-state qz-inline-state--error">{error}</div> : null}{questions.map((question, index) => <Card className="qz-attempt-question" key={question.id}><h3>{index + 1}. {question.prompt}</h3><span>{question.points} poin</span><AnswerInput question={question} value={answers[question.id]} onChange={(value) => setAnswers((current) => ({ ...current, [question.id]: value }))} /></Card>)}{quiz ? <Button disabled={busy} onClick={submit}>{busy ? 'Mengumpulkan...' : 'Kumpulkan jawaban'}</Button> : null}</div>;
}
