import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { QuizIcon } from '../components/icons';
import { Button, Card, Input, PageHeader } from '../components/ui';
import { getLiveSession, joinLiveSession, liveQuizErrorMessage } from '../services/live-quiz.service';

const storageKey = (code) => `quizzy.live.${code.toUpperCase()}`;
export default function QuizJoin() {
  const { code: initialCode = '' } = useParams(); const navigate = useNavigate(); const [code, setCode] = useState(initialCode.toUpperCase()); const [name, setName] = useState(''); const [session, setSession] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { if (initialCode.length !== 6) return; getLiveSession(initialCode).then(setSession).catch((caught) => setError(liveQuizErrorMessage(caught))); }, [initialCode]);
  const inspect = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const normalized = code.trim().toUpperCase(); const found = await getLiveSession(normalized); setSession(found); navigate(`/quiz/join/${normalized}`, { replace: true }); } catch (caught) { setError(liveQuizErrorMessage(caught)); } finally { setBusy(false); } };
  const join = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const normalized = code.trim().toUpperCase(); const joined = await joinLiveSession(normalized, name); sessionStorage.setItem(storageKey(normalized), JSON.stringify(joined.participant)); navigate(`/quiz/play/${normalized}`, { replace: true }); } catch (caught) { setError(liveQuizErrorMessage(caught)); } finally { setBusy(false); } };
  return <main className="qz-live-public qz-enter"><PageHeader eyebrow="QUIZZY LIVE" title="Gabung kuis" description="Cukup masukkan kode dari host atau buka tautan/QR. Tidak perlu login dan tidak perlu masuk kelas." />
    <Card className="qz-live-join"><div className="qz-live-join__mark"><QuizIcon size={31} /></div>{error ? <div className="qz-inline-state qz-inline-state--error">{error}</div> : null}{!session ? <form onSubmit={inspect}><Input label="Kode kuis" placeholder="Contoh: AB2CDE" value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} inputMode="text" autoCapitalize="characters" maxLength={6} autoFocus /><Button block disabled={busy || code.length !== 6} type="submit">{busy ? 'Memeriksa kode...' : 'Lanjutkan'}</Button></form> : <form onSubmit={join}><span className="qz-eyebrow">SESI DITEMUKAN</span><h2>{session.title}</h2><p>{session.questionCount} soal · {session.participantCount} peserta sudah bergabung</p><Input label="Namamu" placeholder="Contoh: Aulia" value={name} onChange={(event) => setName(event.target.value)} maxLength={60} autoFocus /><Button block disabled={busy || name.trim().length < 2} type="submit">{busy ? 'Menghubungkan...' : 'Masuk ke lobi'}</Button><button type="button" className="qz-live-link" onClick={() => { setSession(null); setError(''); }}>Gunakan kode lain</button></form>}</Card></main>;
}
