import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Card, Dialog, PageHeader, Progress, buttonClassName } from '../components/ui';
import { initialiseArrangeAnswers } from '../features/quiz/runtime';
import { getQuiz, quizErrorMessage, submitQuiz } from '../services/quiz.service';

function ArrangeAnswer({ question, value, onChange }) {
  const [dragging, setDragging] = useState(null); const order = Array.isArray(value) ? value : []; const items = new Map((question.items || []).map((item) => [item.id, item]));
  const move = (from, to) => { const next = [...order]; const [item] = next.splice(from, 1); next.splice(to, 0, item); onChange(next); };
  return <ol className="qz-arrange-answer">{order.map((id, index) => <li key={id} draggable onDragStart={() => setDragging(index)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); if (dragging !== null) move(dragging, index); setDragging(null); }}><span>⠿</span>{items.get(id)?.text}<button type="button" aria-label="Naik" disabled={index === 0} onClick={() => move(index, index - 1)}>↑</button><button type="button" aria-label="Turun" disabled={index === order.length - 1} onClick={() => move(index, index + 1)}>↓</button></li>)}</ol>;
}
function HotspotAnswer({ question, value, onChange }) {
  const choose = (event) => { const box = event.currentTarget.getBoundingClientRect(); onChange({ x: Math.max(0, Math.min(100, ((event.clientX - box.left) / box.width) * 100)), y: Math.max(0, Math.min(100, ((event.clientY - box.top) / box.height) * 100)) }); };
  return <div className="qz-hotspot-answer" onClick={choose}><img src={question.imageUrl} alt="Gambar untuk dijawab" /><span className="qz-hotspot-answer__hint">Klik bagian yang menurutmu benar</span>{value && typeof value === 'object' ? <i style={{ left: `${value.x}%`, top: `${value.y}%` }} /> : null}</div>;
}
function AnswerInput({ question, value, onChange }) {
  if (question.type === 'multiple_choice') return <div className="qz-choice-list">{question.choices.map((choice) => <label key={choice}><input type="radio" name={question.id} checked={value === choice} onChange={() => onChange(choice)} /> {choice}</label>)}</div>;
  if (question.type === 'true_false') return <div className="qz-choice-list">{['true', 'false'].map((item) => <label key={item}><input type="radio" name={question.id} checked={String(value) === item} onChange={() => onChange(item === 'true')} /> {item === 'true' ? 'Benar' : 'Salah'}</label>)}</div>;
  if (question.type === 'arrange') return <ArrangeAnswer question={question} value={value} onChange={onChange} />;
  if (question.type === 'image_hotspot') return <HotspotAnswer question={question} value={value} onChange={onChange} />;
  return <input className="qz-answer-input" value={value || ''} onChange={(event) => onChange(event.target.value)} placeholder="Tulis jawabanmu" />;
}
function answered(value) { return Array.isArray(value) ? value.length > 0 : value && typeof value === 'object' ? true : value !== '' && value !== undefined && value !== null; }

export default function QuizAttempt() {
  const { classId, quizId } = useParams(); const [quiz, setQuiz] = useState(null); const [answers, setAnswers] = useState({}); const [activeIndex, setActiveIndex] = useState(0); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(true); const [confirmOpen, setConfirmOpen] = useState(false);
  useEffect(() => { const controller = new AbortController(); getQuiz(classId, quizId, { signal: controller.signal }).then(setQuiz).catch((caught) => { if (caught.name !== 'AbortError') setError(quizErrorMessage(caught)); }).finally(() => setBusy(false)); return () => controller.abort(); }, [classId, quizId]);
  const questions = useMemo(() => { if (!quiz) return []; const items = [...quiz.questions]; if (!quiz.settings?.shuffleQuestions) return items; for (let index = items.length - 1; index > 0; index -= 1) { const random = new Uint32Array(1); crypto.getRandomValues(random); const target = random[0] % (index + 1); [items[index], items[target]] = [items[target], items[index]]; } return items; }, [quiz]);
  useEffect(() => { if (questions.length) setAnswers((current) => initialiseArrangeAnswers(questions, current)); }, [questions]);
  const submit = async () => { setConfirmOpen(false); setBusy(true); setError(''); try { setResult(await submitQuiz(classId, quizId, questions.map((question) => ({ questionId: question.id, answer: answers[question.id] ?? '' })))); } catch (caught) { setError(quizErrorMessage(caught)); } finally { setBusy(false); } };
  const activeQuestion = questions[activeIndex]; const answeredCount = questions.filter((question) => answered(answers[question.id])).length;
  if (result) return <div className="qz-dashboard qz-enter"><PageHeader eyebrow="Hasil kuis" title={quiz.title} description="Jawabanmu sudah dinilai oleh Nalaro Class." /><Card className="qz-quiz-score"><span>Nilai akhir</span><strong>{result.score}</strong><p>{result.passed ? 'Kamu mencapai nilai kelulusan.' : 'Nilaimu belum mencapai batas kelulusan.'}</p><small>{result.earnedPoints} dari {result.totalPoints} poin</small></Card>{result.review?.map((item, index) => <Card className="qz-review" key={item.questionId}><strong>{index + 1}. {item.prompt}</strong><p>Jawabanmu: {Array.isArray(item.answer) ? item.answer.join(' → ') : typeof item.answer === 'object' ? 'Titik pada gambar' : String(item.answer) || 'Tidak dijawab'}</p><p>Jawaban benar: {Array.isArray(item.correctAnswer) ? item.correctAnswer.join(' → ') : String(item.correctAnswer)}</p>{item.explanation ? <small>{item.explanation}</small> : null}</Card>)}<Link className={buttonClassName({ variant: 'secondary' })} to={`/student/classes/${classId}/quizzes`}>Kembali ke daftar kuis</Link></div>;
  return <div className="qz-dashboard qz-enter"><PageHeader eyebrow="Kuis mandiri" title={quiz?.title || 'Memuat kuis...'} description={quiz?.description} actions={<Link className={buttonClassName({ variant: 'secondary' })} to={`/student/classes/${classId}/quizzes`}>Keluar</Link>} />{error ? <div className="qz-inline-state qz-inline-state--error" role="alert">{error}</div> : null}{quiz && activeQuestion ? <div className="qz-attempt"><Card className="qz-attempt__progress"><Progress value={activeIndex + 1} max={questions.length} label={`Soal ${activeIndex + 1} dari ${questions.length} · ${answeredCount} terjawab`} /><div className="qz-attempt-navigator" aria-label="Navigasi soal">{questions.map((question, index) => <button key={question.id} type="button" className={`${index === activeIndex ? 'is-active ' : ''}${answered(answers[question.id]) ? 'is-answered' : ''}`.trim()} aria-label={`Buka soal ${index + 1}${answered(answers[question.id]) ? ', sudah dijawab' : ', belum dijawab'}`} aria-current={index === activeIndex ? 'step' : undefined} onClick={() => setActiveIndex(index)}>{index + 1}</button>)}</div></Card><Card className="qz-attempt-question"><div className="qz-attempt-question__head"><span className="qz-eyebrow">SOAL {activeIndex + 1}</span><span>{activeQuestion.points} poin</span></div><h2>{activeQuestion.prompt}</h2>{activeQuestion.imageUrl && activeQuestion.type !== 'image_hotspot' ? <img className="qz-question-image__player" src={activeQuestion.imageUrl} alt="Ilustrasi soal" /> : null}<AnswerInput question={activeQuestion} value={answers[activeQuestion.id]} onChange={(value) => setAnswers((current) => ({ ...current, [activeQuestion.id]: value }))} /><div className="qz-attempt-actions"><Button variant="secondary" disabled={activeIndex === 0 || busy} onClick={() => setActiveIndex((index) => index - 1)}>Sebelumnya</Button>{activeIndex < questions.length - 1 ? <Button disabled={busy} onClick={() => setActiveIndex((index) => index + 1)}>Soal berikutnya</Button> : <Button disabled={busy} onClick={() => setConfirmOpen(true)}>Tinjau & kumpulkan</Button>}</div></Card></div> : null}<Dialog open={confirmOpen} onClose={() => setConfirmOpen(false)} title="Kumpulkan jawaban?" description={`${answeredCount} dari ${questions.length} soal sudah terjawab.`} footer={<><Button variant="secondary" onClick={() => setConfirmOpen(false)}>Periksa lagi</Button><Button disabled={busy} onClick={submit}>{busy ? 'Mengumpulkan...' : 'Kumpulkan sekarang'}</Button></>}><p className="qz-dialog__copy">Soal yang belum dijawab tetap dapat dikumpulkan sebagai kosong.</p></Dialog></div>;
}
