import { badRequest } from '../http/errors.js';
const TYPES = new Set(['multiple_choice', 'true_false', 'short_answer', 'arrange', 'image_hotspot']);
const text = (value) => typeof value === 'string' ? value.trim() : '';
const https = (value) => /^https:\/\/.{1,2000}$/i.test(value);
export function validateQuizId(value) { if (typeof value !== 'string' || value.length > 64 || !/^[A-Za-z0-9-]+$/.test(value)) throw badRequest('INVALID_QUIZ_ID', 'Identitas kuis tidak valid.'); return value; }
function answer(value) { if (typeof value === 'boolean') return value; if (typeof value === 'string') return text(value); if (Array.isArray(value)) return value.map(text).filter(Boolean).slice(0, 12); if (value && typeof value === 'object' && Number.isFinite(Number(value.x)) && Number.isFinite(Number(value.y))) return { x: Number(value.x), y: Number(value.y) }; return ''; }
export function validateQuizInput(input) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) throw badRequest('INVALID_BODY', 'Data kuis tidak valid.');
  const title = text(input.title).replace(/\s+/g, ' '); const description = text(input.description); const status = text(input.status) || 'draft'; const raw = Array.isArray(input.questions) ? input.questions : []; const errors = {}; const ids = new Set();
  if (title.length < 3 || title.length > 120) errors.title = 'Judul kuis harus terdiri dari 3-120 karakter.'; if (description.length > 500) errors.description = 'Deskripsi maksimal 500 karakter.'; if (!['draft', 'published'].includes(status)) errors.status = 'Status kuis tidak valid.'; if (raw.length > 30) errors.questions = 'Kuis maksimal memiliki 30 soal.';
  const questions = raw.slice(0, 30).map((question, index) => { const key = `questions.${index}`; const type = text(question?.type); const id = text(question?.id) || `q-${index + 1}`; const prompt = text(question?.prompt); const explanation = text(question?.explanation); const points = Number(question?.points ?? 1); const choices = type === 'multiple_choice' && Array.isArray(question?.choices) ? question.choices.map(text) : []; const items = type === 'arrange' && Array.isArray(question?.items) ? question.items.map((item, i) => ({ id: text(item?.id) || `item-${i + 1}`, text: text(item?.text) })) : []; const correctOrder = type === 'arrange' && Array.isArray(question?.correctOrder) ? question.correctOrder.map(text).filter(Boolean) : []; const imageUrl = text(question?.imageUrl); const hotspots = type === 'image_hotspot' && Array.isArray(question?.hotspots) ? question.hotspots.map((spot, i) => ({ id: text(spot?.id) || `area-${i + 1}`, label: text(spot?.label), x: Number(spot?.x), y: Number(spot?.y), width: Number(spot?.width), height: Number(spot?.height), correct: Boolean(spot?.correct) })) : []; const tolerancePercent = type === 'image_hotspot' ? Number(question?.tolerancePercent ?? 2) : 0; const correctAnswer = type === 'true_false' ? Boolean(question?.correctAnswer) : text(question?.correctAnswer);
    if (!TYPES.has(type)) errors[`${key}.type`] = 'Jenis soal tidak didukung.'; if (!/^[A-Za-z0-9_-]{1,64}$/.test(id) || ids.has(id)) errors[`${key}.id`] = 'Identitas soal harus unik dan valid.'; ids.add(id); if ((status === 'published' && prompt.length < 3) || prompt.length > 1000) errors[`${key}.prompt`] = 'Pertanyaan harus terdiri dari 3-1.000 karakter.'; if (!Number.isInteger(points) || points < 1 || points > 100) errors[`${key}.points`] = 'Poin harus berupa angka bulat 1-100.'; if (explanation.length > 1000) errors[`${key}.explanation`] = 'Pembahasan maksimal 1.000 karakter.';
    if (type === 'multiple_choice' && ((status === 'published' && (choices.length < 2 || choices.some((choice) => !choice) || !choices.includes(correctAnswer))) || choices.length > 6 || choices.some((choice) => choice.length > 300))) errors[`${key}.choices`] = 'Pilihan jawaban atau jawaban benar tidak valid.';
    if (type === 'short_answer' && ((status === 'published' && !correctAnswer) || correctAnswer.length > 300)) errors[`${key}.correctAnswer`] = 'Jawaban benar wajib diisi dan maksimal 300 karakter.';
    if (type === 'arrange') { const itemIds = items.map((item) => item.id); const ordered = correctOrder.length === itemIds.length && new Set(correctOrder).size === itemIds.length && correctOrder.every((itemId) => itemIds.includes(itemId)); if (items.length > 10 || items.some((item) => !/^[A-Za-z0-9_-]{1,64}$/.test(item.id) || !item.text || item.text.length > 300) || new Set(itemIds).size !== itemIds.length || (status === 'published' && (items.length < 3 || !ordered))) errors[`${key}.items`] = 'Susunan harus berisi 3-10 item unik dengan urutan jawaban lengkap.'; }
    if (imageUrl && !https(imageUrl)) errors[`${key}.imageUrl`] = 'Gambar soal harus menggunakan URL HTTPS yang valid.';
    if (type === 'image_hotspot') { const valid = (spot) => /^[A-Za-z0-9_-]{1,64}$/.test(spot.id) && spot.label.length <= 80 && [spot.x, spot.y, spot.width, spot.height].every(Number.isFinite) && spot.x >= 0 && spot.y >= 0 && spot.width >= 2 && spot.height >= 2 && spot.x + spot.width <= 100 && spot.y + spot.height <= 100; if ((status === 'published' && (!https(imageUrl) || hotspots.length < 1 || hotspots.filter((spot) => spot.correct).length !== 1)) || hotspots.length > 8 || hotspots.some((spot) => !valid(spot)) || new Set(hotspots.map((spot) => spot.id)).size !== hotspots.length || !Number.isFinite(tolerancePercent) || tolerancePercent < 0 || tolerancePercent > 10) errors[`${key}.hotspots`] = 'Peta klik memerlukan gambar HTTPS dan satu area benar yang valid.'; }
    return { id, type, prompt, choices, correctAnswer, items, correctOrder, imageUrl, hotspots, tolerancePercent, explanation, points }; });
  if (status === 'published' && !questions.length) errors.questions = 'Tambahkan minimal satu soal sebelum menerbitkan kuis.'; const settings = { shuffleQuestions: Boolean(input.settings?.shuffleQuestions), showCorrectAnswers: input.settings?.showCorrectAnswers !== false, passingScore: Number(input.settings?.passingScore ?? 70) }; if (!Number.isInteger(settings.passingScore) || settings.passingScore < 0 || settings.passingScore > 100) errors['settings.passingScore'] = 'Nilai kelulusan harus berupa angka bulat 0-100.'; if (JSON.stringify(questions).length > 120000) errors.questions = 'Isi kuis terlalu besar.'; if (Object.keys(errors).length) throw badRequest('VALIDATION_ERROR', 'Periksa kembali kuis.', errors); return { title, description, status, mode: 'self_paced', questions, settings };
}
export function validateAttempt(input) { if (!input || typeof input !== 'object' || Array.isArray(input) || !Array.isArray(input.answers)) throw badRequest('INVALID_BODY', 'Jawaban kuis tidak valid.'); if (input.answers.length > 30) throw badRequest('VALIDATION_ERROR', 'Jawaban melebihi jumlah soal.'); const answers = input.answers.map((item) => ({ questionId: text(item?.questionId), answer: answer(item?.answer) })); if (answers.some((item) => !/^[A-Za-z0-9_-]{1,64}$/.test(item.questionId))) throw badRequest('VALIDATION_ERROR', 'Identitas soal tidak valid.'); return { answers }; }
